# Generated by Django 2.2.4 on 2019-09-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='headword',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
