# Generated by Django 2.2.4 on 2019-09-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0002_auto_20190901_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='headword',
            field=models.CharField(max_length=200),
        ),
    ]
